### ISSUE TITLE
Images of Eigenspaces

### ISSUE THREAD

**Issue by Bharathi-A-7** [AshishSinha5/eigen_update#1]
Hi, 

Do you have the code to generate the images of Eigenspaces after conversion ? I am unable to get the output images. 

Could you please share the code to generate the same? It will be very helpful to study.

Thank you.

**Comment by AshishSinha5** [comment]
Hi,

You can create Eigenfaces using something like- 

`img = Image.fromarray(((U[:,i]*w[i]).reshape(200,180)).astype('int8'), mode = 'L')`

U is the Eigenvector and W is the wt
You can reconstruct the image using - 

`img = Image.fromarray(((U[:,:i]@w[:i]).reshape(200,180)).astype('int8'), mode = 'L')`

where I runs for number of wt vectors (or eigenvector) we have for the image
